ALL:
	dtc -I dts -O dtb -o i2c1-400hz-00A0.dtbo i2c1-400hz-00A0.dts
	dtc -I dts -O dtb -o i2c2-400hz-00A0.dtbo i2c2-400hz-00A0.dts
	cp i2c1-400hz-00A0.dts /lib/firmware
	cp i2c1-400hz-00A0.dtbo /lib/firmware
	cp i2c2-400hz-00A0.dts /lib/firmware
	cp i2c2-400hz-00A0.dtbo /lib/firmware

