ALL:
	dtc -I dts -O dtb -o SPI0-00A0.dtbo SPI0-00A0.dts
	dtc -I dts -O dtb -o SPI1-00A0.dtbo SPI1-00A0.dts
	cp SPI0-00A0.dts /lib/firmware
	cp SPI0-00A0.dtbo /lib/firmware
	cp SPI1-00A0.dts /lib/firmware
	cp SPI1-00A0.dtbo /lib/firmware

